name: Profile Generator

on:
  schedule:
    - cron: "0 0 * * 1"  # Runs weekly on Mondays
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - main
      - master

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      # Install canvas dependency (required by Platane/snk)
      - name: Install canvas module
        run: |
          sudo apt-get update
          sudo apt-get install -y libpango1.0-dev libcairo2-dev libjpeg-dev libgif-dev
          npm install canvas

      # Generate Snake Animation (Updated Action Version)
      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-snake.svg, dist/github-snake-dark.svg, dist/github-snake-grid.svg, dist/ocean.gif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Generate 3D Contribution Chart
      - name: Generate 3D Contribution Chart
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          MAX_LOADING: 7
          SETTING_JSON: dist/settings.json

      # Generate Profile Trophy (with achievements, languages, etc.)
      - name: Generate Profile Trophy
        uses: lowlighter/metrics@latest
        with:
          filename: dist/metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: B

      # Optimize SVG files
      - name: Optimize SVGs
        run: |
          sudo apt-get update && sudo apt-get install -y svgo
          svgo dist/*.svg

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: output
          clean: true
          single-commit: true
          git-config-name: github-actions[bot]
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
          commit-message: "chore: update profile animations and metrics"

      # Clean up
      - name: Clean up
        if: always()
        run: rm -rf dist/
