# .github/workflows/profile-generator.yml
name: Profile Generator

on:
  schedule:
    - cron: "0 0 */7 * *"  # Runs weekly
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - main
      - master

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Output
        run: |
          mkdir -p dist
          if [ ! -f "dist/github-snake.svg" ] || [ ! -f "dist/github-snake-dark.svg" ]; then
            echo "Failed to generate snake animation"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          target-folder: output
          branch: output
          clean: true
          single-commit: true
          git-config-name: github-actions[bot]
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
          commit-message: "chore: update snake animation"

      - name: Clean up
        if: always()
        run: rm -rf dist/
